// <auto-generated />
using System;
using CharacterSheetDnD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CharacterSheetDnD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240402154259_Skills")]
    partial class Skills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterSavingThrow", b =>
                {
                    b.Property<int>("CharacterSavingThrowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterSavingThrowID"));

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<bool>("IsProficient")
                        .HasColumnType("bit");

                    b.Property<int>("SavingThrowID")
                        .HasColumnType("int");

                    b.HasKey("CharacterSavingThrowID");

                    b.HasIndex("CharacterID");

                    b.HasIndex("SavingThrowID");

                    b.ToTable("CharacterSavingThrows");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterID"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bonds")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Deity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<string>("Eyes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Flaws")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ideals")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalityTraits")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CharacterID");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterClass", b =>
                {
                    b.Property<int>("CharacterClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterClassId"));

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Subclass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CharacterClassId");

                    b.HasIndex("CharacterID");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterHealth", b =>
                {
                    b.Property<int>("HealthID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthID"));

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("MaximumHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("int");

                    b.HasKey("HealthID");

                    b.HasIndex("CharacterID")
                        .IsUnique();

                    b.ToTable("CharacterHealths");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterSkillID"));

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<bool>("IsProficient")
                        .HasColumnType("bit");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("CharacterSkillID");

                    b.HasIndex("CharacterID");

                    b.HasIndex("SkillID");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterStatistic", b =>
                {
                    b.Property<int>("StatisticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatisticID"));

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("StatisticID");

                    b.HasIndex("CharacterID")
                        .IsUnique();

                    b.ToTable("CharacterStatistics");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.SavingThrow", b =>
                {
                    b.Property<int>("SavingThrowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavingThrowID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SavingThrowID");

                    b.ToTable("SavingThrows");

                    b.HasData(
                        new
                        {
                            SavingThrowID = 1,
                            Description = "Used for physical tasks and resisting physical force",
                            Name = "Strength"
                        },
                        new
                        {
                            SavingThrowID = 2,
                            Description = "Used for agility, reflexes, and balance tasks",
                            Name = "Dexterity"
                        },
                        new
                        {
                            SavingThrowID = 3,
                            Description = "Used for endurance and health",
                            Name = "Constitution"
                        },
                        new
                        {
                            SavingThrowID = 4,
                            Description = "Used for memory and reasoning",
                            Name = "Intelligence"
                        },
                        new
                        {
                            SavingThrowID = 5,
                            Description = "Used for perception and insight",
                            Name = "Wisdom"
                        },
                        new
                        {
                            SavingThrowID = 6,
                            Description = "Used for interaction and leadership",
                            Name = "Charisma"
                        });
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillID = 1,
                            Description = "Dexterity checks for staying on your feet in tricky situations.",
                            Name = "Acrobatics"
                        },
                        new
                        {
                            SkillID = 2,
                            Description = "Wisdom checks for calming down animals, understanding their intentions, or predicting their actions.",
                            Name = "Animal Handling"
                        },
                        new
                        {
                            SkillID = 3,
                            Description = "Intelligence checks for recalling lore about spells, magic items, eldritch symbols, magical traditions, the planes of existence, and the inhabitants of those planes.",
                            Name = "Arcana"
                        },
                        new
                        {
                            SkillID = 4,
                            Description = "Strength checks for climbing, jumping, or swimming.",
                            Name = "Athletics"
                        },
                        new
                        {
                            SkillID = 5,
                            Description = "Charisma checks when you try to lie, bluff, or mislead someone.",
                            Name = "Deception"
                        },
                        new
                        {
                            SkillID = 6,
                            Description = "Intelligence checks for recalling lore about historical events, legendary people, ancient kingdoms, past disputes, recent wars, and lost civilizations.",
                            Name = "History"
                        },
                        new
                        {
                            SkillID = 7,
                            Description = "Wisdom checks for determining the true intentions of a creature, such as when searching out a lie or predicting someone’s next move.",
                            Name = "Insight"
                        },
                        new
                        {
                            SkillID = 8,
                            Description = "Charisma checks for influencing someone through overt threats, hostile actions, and physical violence.",
                            Name = "Intimidation"
                        },
                        new
                        {
                            SkillID = 9,
                            Description = "Intelligence checks for looking around for clues and making deductions based on those clues.",
                            Name = "Investigation"
                        },
                        new
                        {
                            SkillID = 10,
                            Description = "Wisdom checks for stabilizing a dying companion or diagnosing an illness.",
                            Name = "Medicine"
                        },
                        new
                        {
                            SkillID = 11,
                            Description = "Intelligence checks for recalling lore about terrain, plants and animals, the weather, and natural cycles.",
                            Name = "Nature"
                        },
                        new
                        {
                            SkillID = 12,
                            Description = "Wisdom checks for noticing things.",
                            Name = "Perception"
                        },
                        new
                        {
                            SkillID = 13,
                            Description = "Charisma checks for delighting an audience with music, dance, acting, storytelling, or some other form of entertainment.",
                            Name = "Performance"
                        },
                        new
                        {
                            SkillID = 14,
                            Description = "Charisma checks for influencing someone or a group of people with tact, social graces, or good nature.",
                            Name = "Persuasion"
                        },
                        new
                        {
                            SkillID = 15,
                            Description = "Intelligence checks for recalling lore about deities, rites and prayers, religious hierarchies, holy symbols, and the practices of secret cults.",
                            Name = "Religion"
                        },
                        new
                        {
                            SkillID = 16,
                            Description = "Dexterity checks for tasks like planting something on someone else or concealing an object on your person.",
                            Name = "Sleight of Hand"
                        },
                        new
                        {
                            SkillID = 17,
                            Description = "Dexterity checks for hiding or moving silently.",
                            Name = "Stealth"
                        },
                        new
                        {
                            SkillID = 18,
                            Description = "Wisdom checks for following tracks, hunting wild game, guiding your group through frozen wastelands, identifying signs that owlbears live nearby, predicting the weather, or avoiding quicksand and other natural hazards.",
                            Name = "Survival"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CharacterSavingThrow", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.Character", "Character")
                        .WithMany("CharacterSavingThrows")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharacterSheetDnD.Models.SavingThrow", "SavingThrow")
                        .WithMany("CharacterSavingThrows")
                        .HasForeignKey("SavingThrowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("SavingThrow");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.Character", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterClass", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.Character", "Character")
                        .WithMany("CharacterClasses")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterHealth", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.Character", "Character")
                        .WithOne("CharacterHealth")
                        .HasForeignKey("CharacterSheetDnD.Models.CharacterHealth", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterSkill", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.Character", "Character")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharacterSheetDnD.Models.Skill", "Skill")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.CharacterStatistic", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.Character", "Character")
                        .WithOne("CharacterStatistic")
                        .HasForeignKey("CharacterSheetDnD.Models.CharacterStatistic", "CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharacterSheetDnD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CharacterSheetDnD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.Character", b =>
                {
                    b.Navigation("CharacterClasses");

                    b.Navigation("CharacterHealth");

                    b.Navigation("CharacterSavingThrows");

                    b.Navigation("CharacterSkills");

                    b.Navigation("CharacterStatistic");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.SavingThrow", b =>
                {
                    b.Navigation("CharacterSavingThrows");
                });

            modelBuilder.Entity("CharacterSheetDnD.Models.Skill", b =>
                {
                    b.Navigation("CharacterSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
